name: Report Metrics

on: [workflow_dispatch]

jobs:
  report:
    name: Slack
    runs-on: ubuntu-latest

    steps:
      - uses: Addepar/github-metrics@v1.2.0
        with:
          github-owner: bantic
          github-repo: github-metrics
          github-token: ${{secrets.GITHUB_TOKEN}}
          slack-app-token: ${{secrets.SLACK_APP_TOKEN}}
          slack-channel-id: ${{secrets.SLACK_CHANNEL_ID}}
          post-to-slack: "false"
          log-debug-messages: "true"
